### ISSUE TITLE
lampe-gtk: port features from cli-version

### ISSUE THREAD

**Issue by poinck** [poinck/lampe#10]
port all functionallity from the cli-version (bash) to gtk-version (vala)
- [ ] #2 hue-bridge discovery and configuration
- [ ] #3 user configuration
- [ ] #7 alarm clock
- [x] #8 support more than 9 lights
- [ ] #9 support group of lights
- [ ] #13 find new lights
- [x] #14 global on/off switch
- [ ] #12 some sequences
